apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-service-deployment
  labels:
    app: registry-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registry-service
  template:
    metadata:
      labels:
        app: registry-service
    spec:
      containers:
      - name: registry-service
        image: oauth-registry-ms
        ports:
        - containerPort: 8080