server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: oauth-registry-ms
    
eureka:
  instance:
    hostname: "${HOSTNAME}.eureka"
  client:
    serviceUrl: 
      defaultZone: ${EUREKA_SERVER_ADDRESS} 
    fetch-registry: false
    register-with-eureka: false
      