apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-api-gateway-cm
data:
  eureka_service_address: http://eureka-0.eureka:8761/eureka

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-api-gateway-app
  labels:
    app: oauth-api-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : oauth-api-gateway-app
  template:
    metadata:
      labels:
        app: oauth-api-gateway-app
    spec:
      containers:
      - name: oauth-api-gateway-app
        image: oauth-api-gateway:1.0.0
        imagePullPolicy: Never
        ports:
          - containerPort: 9191
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: oauth-api-gateway-cm
                key: eureka_service_address 

---
apiVersion: v1
kind: Service
metadata:
  name: oauth-api-gateway-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9191
      protocol: TCP
  selector:
    app: oauth-api-gateway-app