apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB_HOST_NAME: postgres
  POSTGRES_DB_USER_MS: userdb
  POSTGRES_DB_DRIVER_CLASS_NAME: org.postgresql.Driver
  POSTGRES_DB_HIBERNATE_DATABASE_DIALECT: org.hibernate.dialect.PostgreSQL82Dialect

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-credentials
data:
  POSTGRES_USERNAME: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
    tier: database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    tier: database
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
    tier: database
  clusterIP: None