server:
  port: 8180
  
spring:
  datasource:    url: ${USER.MS.DATABASE.URL:jdbc:h2:mem:usermsdb}
    username: ${USER.MS.DATABASE.USERNAME:sa}
    password: ${USER.MS.DATABASE.PASSWORD:}
    driver-class-name: ${USER.MS.DATABASE.DRIVER-CLASS-NAME:org.h2.Driver}
  jpa:
    properties:      hibernate:
        dialect: ${USER.MS.DATABASE.DIALECT:org.hibernate.dialect.H2Dialect}    hibernate:      ddl-auto: update
      naming:        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    generate-ddl: true
    show-sql: true
  h2:    console:      enabled: true
      path: /h2-console
      
oauth:
  validityInSeconds:
    accessTokenValiditySeconds: 60
    refreshTokenValiditySeconds: 86400
    
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/