server:
  port: ${SERVER_PORT:9002}

spring:
  datasource:    url: jdbc:postgresql://${USER_MS_DATABASE_HOST}:5432/${USER_MS_DATABASE_NAME}
    username: ${USER_MS_DATABASE_USERNAME}
    password: ${USER_MS_DATABASE_PASSWORD}
    driver-class-name: ${USER_MS_DATABASE_DRIVER_CLASS_NAME}
  jpa:
    properties:      hibernate:
        dialect: ${USER_MS_DATABASE_DIALECT:org.hibernate.dialect.H2Dialect}    hibernate:      ddl-auto: update
      naming:        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    generate-ddl: true
    show-sql: true
  h2:    console:      enabled: true
      path: /h2-console
      
oauth:
  validityInSeconds:
    accessTokenValiditySeconds: 60
    refreshTokenValiditySeconds: 86400
    
eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka